# ADGSTUDIOS 2022 - config.yaml
themes:
  - theme: vanilla
    path: themes/vanilla.docx
    # This is the default theme, so it will be used if no theme is specified
    default: true

linkedin_profile:  
  # LinkedIn profile URL
  url: https://za.linkedin.com/in/adgsenpai

info:  
  phone: +27605224922
  email: adg@adgstudios.co.za
  location: Somerset West, Western Cape, South Africa
  discord: adgsenpai#2940
  instant: +27605224922
  website: https://adgstudios.co.za
  headline: Mathematican and Computer Scientist
  
  